### ISSUE TITLE
FR: Close current tab 

### ISSUE THREAD

**Issue by javiavid** [Sheeplet1/obsidian-pin-enhancer#1]
Is it possible to prevent them from closing with the Close current tab command?

Just as in browser tabs, the CTRL+W hotkey is often used a lot to close multiple tabs consecutively and it would be great if it prevented them from closing.

**Comment by Sheeplet1** [comment]
do you mean the "Close current tab" command in the command palette?
I can't block "Ctrl-W" as its a bit invasive so theres a hotkey "Close tab" to bind to instead

**Comment by javiavid** [comment]
That works for me, thank you
