### ISSUE TITLE
`cmd` + `w`

### ISSUE THREAD

**Issue by KulySocc** [Sheeplet1/obsidian-pin-enhancer#2]
Mhm, I like your plugin, it's weird, that this is not a default behaviour of obsidian.
But it's kind of a bummer, that you'll still be able to close the tab using `cmd` + `w`. This hotkey sometimes is being used faster than I could think :/

**Comment by Sheeplet1** [comment]
rebind the close tab in hotkeys

**Comment by KulySocc** [comment]
Damn, I see. Thank you.
